/*
    CODIGO PROPIEDAD DE 
            FELIPE LONDOÑO: (https://github.com/Felosque)
            ALEJANDRO LUNA: (https://github.com/AlejoFront)
    
    Agradecimientos a la comunidad de INTERNET por todos sus ejemplos y hacer mucho más facil el apredizaje.
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author felip
 */
public class GUIPanelGrafica extends javax.swing.JPanel {

    private JFreeChart grafica;
    private DefaultPieDataset datos;
    
    private double[] datosDouble;
    /**
     * Creates new form GUIPanelGrafica
     */
    public GUIPanelGrafica(List<Integer> cantidadGenero, int pModo) {
        initComponents();
        setBackground(Color.white);
        if(pModo == 1)
        {
            ponerGraficaGenero(cantidadGenero);
        }else{
            ponerGraficaMateriasPorGrado(cantidadGenero);
        }
    }

    public void ponerGraficaGenero(List<Integer> cantidadGenero)
    {
        datos = new DefaultPieDataset();
        datos.setValue("Hombres", cantidadGenero.get(0));
        datos.setValue("Mujeres", cantidadGenero.get(1));
        grafica = ChartFactory.createPieChart("Estudiantes por género", datos, true, true, false);
        ChartPanel chartPanel = new ChartPanel(grafica);
        chartPanel.setSize(new Dimension(600, 400));
        add(chartPanel);
        this.setSize(chartPanel.getSize());
    }
    
    public void ponerGraficaMateriasPorGrado(List<Integer> cantidadGenero){
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        String grado = "Grado";
        for (int i = 0; i < 11; i++) {
            int d = i + 1;
            dataset.addValue(cantidadGenero.get(i), grado, ""+d);
        }
        grafica = ChartFactory.createBarChart( "Materias por grado", "Grados", "Materias",            
         dataset,          
         PlotOrientation.VERTICAL,           
         true, true, false);
        ChartPanel chartPanel = new ChartPanel(grafica);
        chartPanel.setSize(new Dimension(600, 400));
        add(chartPanel);
        this.setSize(chartPanel.getSize());
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
