/*
    CODIGO PROPIEDAD DE 
            FELIPE LONDOÑO: (https://github.com/Felosque)
            ALEJANDRO LUNA: (https://github.com/AlejoFront)
    
    Agradecimientos a la comunidad de INTERNET por todos sus ejemplos y hacer mucho más facil el apredizaje.
 */
package gui;

import estructural.Matricula;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.ServicioLocalMatricula;

/**
 *
 * @author felip
 */
public class JDialogListarMatriculasTodas extends javax.swing.JFrame {

    /**
     * Creates new form JDialogListarMatriculasTodas
     */
    public JDialogListarMatriculasTodas(){
        initComponents();
        cambiarDatosTabla(ServicioLocalMatricula.darMatriculas());
        setTitle("Lista de matriculas");
        setLocationRelativeTo(null);
        setSize(810, 520);
        
    }

    
    private void cambiarDatosTabla(ArrayList<Matricula> matriculas){

        DefaultTableModel modelo = (DefaultTableModel)tablaDatos.getModel();
        modelo.getDataVector().removeAllElements();
        revalidate();
        if(matriculas != null){
            for (int i = 0; i < matriculas.size(); i++) {
                Vector fila = new Vector();
                fila.add(matriculas.get(i).getCodigo());
                fila.add(matriculas.get(i).getPkEstudiante());
                fila.add(matriculas.get(i).getPkMateria());

                //fila.add(ServicioLocalEstudiante.getServicio().buscarEstudiante(matriculas.get(i).getPkEstudiante()).getNombres());
                //fila.add(ServicioLocalMateria.getServicio().darMateriaPorCodigo(matriculas.get(i).getPkMateria()).getNombre());
                fila.add(matriculas.get(i).getNotaDefinitiva());
                fila.add(matriculas.get(i).getFechaInscripcion());
                fila.add(matriculas.get(i).getFechaInicio());
                fila.add(matriculas.get(i).getFechaFinal());
                String inf = "";
                if(matriculas.get(i).getEstado() == 0){
                    inf = "Matriculada";
                }else if(matriculas.get(i).getEstado() == 1){
                    inf = "Cursando";
                }else if(matriculas.get(i).getEstado() == 2){
                    inf = "Reprobada";
                }else if(matriculas.get(i).getEstado() == 3){
                    inf = "Aprobada";
                }
                fila.add(inf);
                modelo.addRow(fila);
            }
        }
        repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        busquedaDocumento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        estadoBusqueda = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 58, 88));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTA DE MATRICULAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 670, 60));

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Estudiante", "Materia", "Definitiva", "Fecha Inscripción", "Fecha Inicio", "Fecha Final", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 760, 310));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));

        jLabel2.setText("Filtrar por estudiante (documento):");

        busquedaDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busquedaDocumentoKeyReleased(evt);
            }
        });

        jLabel3.setText("Filtrar por estado:");

        estadoBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar Estado", "Cursando", "Reprobada", "Aprobada" }));
        estadoBusqueda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoBusquedaItemStateChanged(evt);
            }
        });

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(busquedaDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(estadoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busquedaDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(estadoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 760, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        cambiarDatosTabla(ServicioLocalMatricula.darMatriculas());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void busquedaDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaDocumentoKeyReleased

        
        cambiarDatosTabla(ServicioLocalMatricula.darMatriculasEstudiante(busquedaDocumento.getText()));
    }//GEN-LAST:event_busquedaDocumentoKeyReleased

    private void estadoBusquedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_estadoBusquedaItemStateChanged
        
        if(estadoBusqueda.getSelectedIndex() != 0){
            cambiarDatosTabla(ServicioLocalMatricula.darMatriculasPorEstado(""+estadoBusqueda.getSelectedIndex()));
        }
    }//GEN-LAST:event_estadoBusquedaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busquedaDocumento;
    private javax.swing.JComboBox estadoBusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
}
